ci: updated how we call tests

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -8,11 +8,11 @@ on:
     branches:
       - trunk
     paths:
-      #This should only run when terraform files have been changed.
       - '**/*.tf'
       - '**/*.tfvars'
       - '**/*.json'
       - '**/*.yaml'
+      - '**/*.tftest.hcl'
   workflow_dispatch:
   release:
     types: [created]
@@ -32,179 +32,75 @@ concurrency:
   group: terraform-plan-apply-destroy
   cancel-in-progress: false
 
+
 jobs:
-  validate:
-    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/trunk')
+  check-changed-files:
     runs-on: ubuntu-latest
-    name: 🔍 Terraform Validate
+    name: 🔍 Check Changed Files
+    outputs:
+      changed_files: ${{ steps.changed-files.outputs.changed_files }}
     steps:
-        - name: Checkout
-          uses: actions/checkout@v4
-    
-        - name: Set up Terraform
-          uses: hashicorp/setup-terraform@v3
-          with:
-            terraform_version: "~1.9.0" 
-    
-        - name: terraform init station module
-          run: terraform init
-    
-        - name: terraform validate station
-          run: terraform validate
-    
-        - name: terraform init station tests
-          run: terraform init
-          working-directory: test
-    
-        - name: terraform validate test tests
-          run: terraform validate
-          working-directory: test      
+      - name: Checkout Repository
+        uses: actions/checkout@v4
 
-  plan:
-    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/trunk')
+      - name: Get Changed Files
+        id: changed-files
+        run: |
+          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
+          echo "Changed files: $CHANGED_FILES"
+          echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV
+
+      - name: Validate File Definitions
+        run: |
+          KNOWN_FILES="variables.tf applications.tf app_role_assignment.tf application/ groups.tf group/ tfe.tf hashicorp/ group_membership.tf user_assigned_identities.tf role_assignment.tf user_assigned_identity/"
+          IGNORED_FILES="README.md LICENSE terraform.tfstate plan.tfplan"
+          for FILE in ${{ env.changed_files }}; do
+            if echo "$IGNORED_FILES" | grep -q "$FILE"; then
+              echo "Ignoring file: $FILE"
+              continue
+            fi
+            if ! echo "$KNOWN_FILES" | grep -q "$FILE"; then
+              echo "Error: Unknown file detected: $FILE"
+              exit 1
+            fi
+          done
+
+  application-test:
+    needs: check-changed-files
+    if: contains(needs.check-changed-files.outputs.changed_files, 'variables.tf') || contains(needs.check-changed-files.outputs.changed_files, 'applications.tf') || contains(needs.check-changed-files.outputs.changed_files, 'app_role_assignment.tf') || contains(needs.check-changed-files.outputs.changed_files, 'application/')
     runs-on: ubuntu-latest
-    needs: validate
-    name: 📈 Terraform Plan Execution for tests
-    environment: E2E_testing
-    env:
-        TFE_ORGANIZATION: ${{ secrets.TFE_ORGANIZATION }}
-        TF_VAR_tfc_organization_name: ${{ secrets.TF_VAR_TFC_ORGANIZATION_NAME }}
-        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
     steps:
-        - name: 'Azure: login'
-          uses: azure/login@v2
-          with:
-            client-id:       ${{ secrets.AZ_CLIENT_ID }}
-            subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
-            tenant-id:       ${{ secrets.AZ_TENANT_ID }}
-    
-        - name: Checkout
-          uses: actions/checkout@v4
-        
-        - name: Append Run ID to Project Name
-          run: echo "TF_VAR_tfc_project_name=${{ secrets.TF_VAR_TFC_PROJECT_NAME }}-${{ github.run_id }}-e2e" >> $GITHUB_ENV
-        
-        - name: Set up Terraform
-          uses: hashicorp/setup-terraform@v3
-          with:
-            terraform_version: "~1.9.0"
-            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
-    
-        - name: terraform init
-          run: terraform init
-          working-directory: test
-    
-        - name: terraform plan
-          run: terraform plan -out plan.tfplan -input=false
-          working-directory: test
-  
-  terraform_test:
-    environment: E2E_testing
-    needs: plan
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+      - name: Run application test
+        run: terraform test -filter tests/application.tftest.hcl
+
+  group-test:
+    needs: check-changed-files
+    if: contains(needs.check-changed-files.outputs.changed_files, 'variables.tf') || contains(needs.check-changed-files.outputs.changed_files, 'groups.tf') || contains(needs.check-changed-files.outputs.changed_files, 'group/')
     runs-on: ubuntu-latest
-    name: 🥼 Terraform tests
-    env:
-        TFE_ORGANIZATION: ${{ secrets.TFE_ORGANIZATION }}
-        TF_VAR_tfc_organization_name: ${{ secrets.TF_VAR_TFC_ORGANIZATION_NAME }}
-        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
     steps:
-        - name: 'Azure: login'
-          uses: azure/login@v2
-          with:
-            client-id:       ${{ secrets.AZ_CLIENT_ID }}
-            subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
-            tenant-id:       ${{ secrets.AZ_TENANT_ID }}
-    
-        - name: Checkout
-          uses: actions/checkout@v4
-        
-        - name: Append Run ID to Project Name
-          run: echo "TF_VAR_tfc_project_name=${{ secrets.TF_VAR_TFC_PROJECT_NAME }}-${{ github.run_id }}-tests" >> $GITHUB_ENV
-        
-        - name: Set up Terraform
-          uses: hashicorp/setup-terraform@v3
-          with:
-            terraform_version: "~1.9.0"
-            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
-        
-        - name: Terraform init
-          run: terraform init
-          
-        - name: Terraform test
-          run: terraform test
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+      - name: Run group test
+        run: terraform test -filter tests/group.tftest.hcl
 
-  apply_and_destroy:
-    if: >
-      (
-        github.event_name == 'workflow_dispatch' ||
-        github.event_name == 'release'
-      ) || (
-        github.event.issue.pull_request &&
-        github.event.comment.body == '/start_e2e'
-      )
-    environment: E2E_testing
-    needs: plan
+  tfe-test:
+    needs: check-changed-files
+    if: contains(needs.check-changed-files.outputs.changed_files, 'variables.tf') || contains(needs.check-changed-files.outputs.changed_files, 'tfe.tf') || contains(needs.check-changed-files.outputs.changed_files, 'hashicorp/')
     runs-on: ubuntu-latest
-    name: 🥼 End-to-End (E2E) Terraform Testing
-    env:
-        TFE_ORGANIZATION: ${{ secrets.TFE_ORGANIZATION }}
-        TF_VAR_tfc_organization_name: ${{ secrets.TF_VAR_TFC_ORGANIZATION_NAME }}
     steps:
-        - name: 'Azure: login'
-          uses: azure/login@v2
-          with:
-            client-id:       ${{ secrets.AZ_CLIENT_ID }}
-            subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
-            tenant-id:       ${{ secrets.AZ_TENANT_ID }}
-    
-        - name: Checkout
-          uses: actions/checkout@v4
-        
-        - name: Append Run ID to Project Name
-          run: echo "TF_VAR_tfc_project_name=${{ secrets.TF_VAR_TFC_PROJECT_NAME }}-${{ github.run_id }}-e2e" >> $GITHUB_ENV
-        
-        - name: Set up Terraform
-          uses: hashicorp/setup-terraform@v3
-          with:
-            terraform_version: "~1.9.0"
-            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
-        
-        - name: terraform init
-          run: terraform init
-          working-directory: test
-          
-        - name: terraform plan
-          run: terraform plan -out plan.tfplan -input=false
-          working-directory: test
-    
-        - name: terraform apply
-          run: terraform apply --auto-approve plan.tfplan
-          working-directory: test
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+      - name: Run tfe test
+        run: terraform test -filter tests/tfe.tftest.hcl
 
-        - name: destroy role definitions
-          if: always()
-          run: |
-            # Deleting the two role definitions created by the test, using 
-            # az cli is much faster than deleting them with Terraform for some reason.
-            az role definition delete --name "Maximum Custom Role provisioned with Station"
-            az role definition delete --name "Minimum Custom Role provisioned with Station"
-          working-directory: test
-
-#        - name: upload state as artifact
-#          uses: actions/upload-artifact@v4
-#          with:
-#            name: state.json
-#            path: test/state.json
-#            retention-days: 1
-
-        - name: terraform plan (destroy)
-          if: always()
-          run: |
-            terraform plan -destroy -out plan.tfplan -input=false
-          working-directory: test
-    
-        - name: terraform destroy
-          if: always()
-          run: |
-            terraform apply --auto-approve plan.tfplan
-          working-directory: test
+  user-assigned-identities-test:
+    needs: check-changed-files
+    if: contains(needs.check-changed-files.outputs.changed_files, 'variables.tf') || contains(needs.check-changed-files.outputs.changed_files, 'group_membership.tf') || contains(needs.check-changed-files.outputs.changed_files, 'user_assigned_identities.tf') || contains(needs.check-changed-files.outputs.changed_files, 'role_assignment.tf') || contains(needs.check-changed-files.outputs.changed_files, 'user_assigned_identity/')
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+      - name: Run user assigned identities test
+        run: terraform test -filter tests/user_assigned_identities.tftest.hcl
